### ISSUE TITLE
openai.error.RateLimitError

### ISSUE THREAD

**Issue by rayane-d** [rsaryev/talk-codebase#18]
I'm getting this error:

? Creating a vector store will cost ~$0.35806. Do you want to continue? Yes
⠹ Creating vector storeRetrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised RateLimitError: Rate limit reached for default-text-embedding-ada-002 in organization org-xxxx on tokens per min. Limit: 150000 / min. Current: 1 / min. Contact us through our help center at help.openai.com if you continue to have issues..
⠼ Creating vector storeRetrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised RateLimitError: Rate limit reached for default-text-embedding-ada-002 in organization org-xxxx on tokens per min. Limit: 150000 / min. Current: 1 / min. Contact us through our help center at help.openai.com if you continue to have issues..
⠧ Creating vector storeRetrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised RateLimitError: Rate limit reached for default-text-embedding-ada-002 in organization org-xxxx on tokens per min. Limit: 150000 / min. Current: 1 / min. Contact us through our help center at help.openai.com if you continue to have issues..
⠧ Creating vector storeRetrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 8.0 seconds as it raised RateLimitError: Rate limit reached for default-text-embedding-ada-002 in organization org-xxxx on tokens per min. Limit: 150000 / min. Current: 0 / min. Contact us through our help center at help.openai.com if you continue to have issues..
⠏ Creating vector storeRetrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 10.0 seconds as it raised RateLimitError: Rate limit reached for default-text-embedding-ada-002 in organization org-xxxx on tokens per min. Limit: 150000 / min. Current: 1 / min. Contact us through our help center at help.openai.com if you continue to have issues..
⠦ Creating vector storeTraceback (most recent call last):
  File "/home/codespace/.python/current/bin/talk-codebase", line 8, in <module>
    sys.exit(main())
  File "/opt/python/3.10.8/lib/python3.10/site-packages/talk_codebase/cli.py", line 65, in main
    raise e
  File "/opt/python/3.10.8/lib/python3.10/site-packages/talk_codebase/cli.py", line 58, in main
    fire.Fire({
  File "/opt/python/3.10.8/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/python/3.10.8/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/talk_codebase/cli.py", line 50, in chat
    llm = factory_llm(root_dir, config)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/talk_codebase/llm.py", line 117, in factory_llm
    return OpenAILLM(root_dir, config)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/talk_codebase/llm.py", line 25, in __init__
    self.vector_store = self._create_store(root_dir)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/talk_codebase/llm.py", line 104, in _create_store
    return self._create_vector_store(embeddings, MODEL_TYPES["OPENAI"], root_dir)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/talk_codebase/llm.py", line 63, in _create_vector_store
    db = FAISS.from_documents(texts, embeddings)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 402, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/langchain/vectorstores/faiss.py", line 567, in from_texts
    embeddings = embedding.embed_documents(texts)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/langchain/embeddings/openai.py", line 508, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=self.deployment)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/langchain/embeddings/openai.py", line 358, in _get_len_safe_embeddings
    response = embed_with_retry(
  File "/opt/python/3.10.8/lib/python3.10/site-packages/langchain/embeddings/openai.py", line 108, in embed_with_retry
    return _embed_with_retry(**kwargs)
  File "/home/codespace/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/home/codespace/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/codespace/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/codespace/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/opt/python/3.10.8/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/opt/python/3.10.8/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/codespace/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/langchain/embeddings/openai.py", line 105, in _embed_with_retry
    response = embeddings.client.create(**kwargs)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/opt/python/3.10.8/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/opt/python/3.10.8/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/opt/python/3.10.8/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: Rate limit reached for default-text-embedding-ada-002 in organization org-xxx on tokens per min. Limit: 150000 / min. Current: 1 / min. Contact us through our help center at help.openai.com if you continue to have issues.

**Comment by rsaryev** [comment]
https://github.com/rsaryev/talk-codebase/commit/b978a7640276ec35dc1ec897e97c13ef6c4b62c4
