### ISSUE TITLE
Creating  vector store for documents error

### ISSUE THREAD

**Issue by yangming0322** [rsaryev/talk-codebase#5]
Traceback (most recent call last):
  File "/Users/tim/anaconda3/envs/local/bin/talk-codebase", line 8, in <module>
⠹ Creating vector store for 2770 documents    sys.exit(main())
  File "/Users/tim/anaconda3/envs/local/lib/python3.10/site-packages/talk_codebase/cli.py", line 98, in main
    raise e
  File "/Users/tim/anaconda3/envs/local/lib/python3.10/site-packages/talk_codebase/cli.py", line 88, in main
    fire.Fire({
  File "/Users/tim/anaconda3/envs/local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/tim/anaconda3/envs/local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/tim/anaconda3/envs/local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/tim/anaconda3/envs/local/lib/python3.10/site-packages/talk_codebase/cli.py", line 82, in chat
    llm = factory_llm(root_dir, config)
  File "/Users/tim/anaconda3/envs/local/lib/python3.10/site-packages/talk_codebase/LLM.py", line 106, in factory_llm
    return OpenAILLM(root_dir, config)
  File "/Users/tim/anaconda3/envs/local/lib/python3.10/site-packages/talk_codebase/LLM.py", line 24, in __init__
    self.vector_store = self._create_store(root_dir)
  File "/Users/tim/anaconda3/envs/local/lib/python3.10/site-packages/talk_codebase/LLM.py", line 95, in _create_store
    return self._create_vector_store(embeddings, MODEL_TYPES["OPENAI"], root_dir)
  File "/Users/tim/anaconda3/envs/local/lib/python3.10/site-packages/talk_codebase/LLM.py", line 74, in _create_vector_store
    db = FAISS.from_documents(texts, embeddings)
  File "/Users/tim/anaconda3/envs/local/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 317, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/Users/tim/anaconda3/envs/local/lib/python3.10/site-packages/langchain/vectorstores/faiss.py", line 502, in from_texts
    return cls.__from(
  File "/Users/tim/anaconda3/envs/local/lib/python3.10/site-packages/langchain/vectorstores/faiss.py", line 454, in __from
    vector = np.array(embeddings, dtype=np.float32)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5951,) + inhomogeneous part.

**Comment by rsaryev** [comment]
Try a different folder path

`talk-codebase chat ./your path`
